spring:
    server:
        port: 8080
        servlet:
            contextPath: /

    spring:
        jpa:
            hibernate:
                ddl-auto: create

    datasource:
        url: jdbc:mysql://localhost:3306/test
        driver-class-name: com.mysql.jdbc.Driver
        database-platform: org.hibernate.dialect.MySQL5Dialect
        username: root
        password: my-secret-pw